name: Medicina - Release Candidate

on:
  workflow_dispatch:
  push:
    tags: 'rc[0-9]+.[0-9]+.[0-9]+'

jobs:
  trigger:
    name: Trigger workflow responsible for rc deploy
    runs-on: ubuntu-latest

    steps:
      - name: Trigger workflow
        uses: mvasigh/dispatch-action@main
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          event_type: deploy_medicina_rc
          message: |
            {
              "commit": "${{ github.sha }}",
              "vertical": "medicina",
              "firebase_token": "medicina-rc-this-is-fake-firebase-token",
              "firebase_ios_app": "medicina-rc-this-is-a-fake-firebase-ios-app",
              "firebase_android_app": "medicina-rc-this-is-a-fake-firebase-android-app",
              "firebase_group": "medicina-rc-this-is-a-fake-firebase-group"
            }