name: Medicina - Sandbox

on:
  workflow_dispatch

jobs:
  trigger:
    name: Trigger workflow responsible for sandbox deploy
    runs-on: ubuntu-latest

    steps:
      - name: Trigger workflow
        uses: mvasigh/dispatch-action@main
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          event_type: deploy_medicina_sandbox
          message: |
            {
              "commit": "${{ github.sha }}",
              "vertical": "medicina",
              "firebase_token": "medicina-sandbox-this-is-fake-firebase-token",
              "firebase_ios_app": "medicina-sandbox-this-is-a-fake-firebase-ios-app",
              "firebase_android_app": "medicina-sandbox-this-is-a-fake-firebase-android-app",
              "firebase_group": "medicina-sandbox-this-is-a-fake-firebase-group"
            }