name: Concursos - Sandbox

on:
  workflow_dispatch

jobs:
  trigger:
    name: Trigger workflow responsible for sandbox deploy
    runs-on: ubuntu-latest

    steps:
      - name: Trigger workflow
        uses: mvasigh/dispatch-action@main
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          event_type: deploy_concursos_sandbox
          message: |
            {
              "vertical": "concursos",
              "firebase_token": "concursos-sandbox-this-is-fake-firebase-token",
              "firebase_ios_app": "concursos-sandbox-this-is-a-fake-firebase-ios-app",
              "firebase_android_app": "concursos-sandbox-this-is-a-fake-firebase-android-app",
              "firebase_group": "concursos-sandbox-this-is-a-fake-firebase-group",
            }